INDEX_HIERARCHY = {
    "Equity": [
        "Broad Market Indices",
        "Sectoral Indices",
        "Strategy Indices",
        "Thematic Indices"
    ],
    "Fixed Income": [
        "Government Securities",
        "Money Market",
        "SDL Indices",
        "Target Maturity Index"
    ],
    "Multi Asset": [
        "Hybrid Indices"
    ]
}
BROAD_MARKET_LIST = [
    "NIFTY 50",
    "NIFTY NEXT 50",
    "NIFTY 100",
    "NIFTY 200",
    "NIFTY 500",
    "NIFTY TOTAL MARKET",
    "NIFTY LARGEMIDCAP 250",
    "NIFTY MIDCAP 50",
    "NIFTY MIDCAP 100",
    "NIFTY MIDCAP 150",
    "NIFTY SMALLCAP 50",
    "NIFTY SMALLCAP 100",
    "NIFTY SMALLCAP 250",
    "NIFTY MIDSMALLCAP 400",
    "NIFTY INDIA FPI 150",
    "NIFTY MICROCAP 250",
    "NIFTY MIDCAP SELECT",
    "NIFTY MIDSMALLCAP400 50:50",
    "NIFTY SMALLCAP 500",
    "NIFTY500 LARGEMIDSMALL EQUAL-CAP WEIGHTED",
    "NIFTY500 MULTICAP 50:25:25"
]

BROAD_MARKET_INDICES = {
    idx: {
        "name": f"{idx} INDEX",
        "indexName": idx
    }
    for idx in BROAD_MARKET_LIST
}
SECTORAL_LIST = [
    "NIFTY AUTO",
    "NIFTY BANK",
    "NIFTY CEMENT",
    "NIFTY CHEMICALS",
    "NIFTY CONSUMER DURABLES",
    "NIFTY FINANCIAL SERVICES",
    "NIFTY FINANCIAL SERVICES 25/50",
    "NIFTY FINANCIAL SERVICES EX-BANK",
    "NIFTY FMCG",
    "NIFTY HEALTHCARE",
    "NIFTY IT",
    "NIFTY MEDIA",
    "NIFTY METAL",
    "NIFTY MIDSMALL FINANCIAL SERVICES",
    "NIFTY MIDSMALL HEALTHCARE",
    "NIFTY MIDSMALL IT & TELECOM",
    "NIFTY OIL & GAS",
    "NIFTY PHARMA",
    "NIFTY PRIVATE BANK",
    "NIFTY PSU BANK",
    "NIFTY REALTY",
    "NIFTY REITS & REALTY",
    "NIFTY500 HEALTHCARE"
]

SECTORAL_INDICES = {
    idx: {
        "name": f"{idx}",
        "indexName": idx
    }
    for idx in SECTORAL_LIST
}
STRATEGY_LIST = [
    "NIFTY 50 ARBITRAGE",
    "NIFTY 50 FUTURES PR",
    "NIFTY 50 FUTURES TR",
    "NIFTY ALPHA 50",
    "NIFTY ALPHA LOW-VOLATILITY 30",
    "NIFTY ALPHA QUALITY LOW-VOLATILITY 30",
    "NIFTY ALPHA QUALITY VALUE LOW-VOLATILITY 30",
    "NIFTY DIVIDEND OPPORTUNITIES 50",
    "NIFTY GROWTH SECTORS 15",
    "NIFTY HIGH BETA 50",
    "NIFTY LOW VOLATILITY 50",
    "NIFTY MIDCAP150 MOMENTUM 50",
    "NIFTY MIDCAP150 QUALITY 50",
    "NIFTY MIDSMALLCAP400 MOMENTUM QUALITY 100",
    "NIFTY QUALITY LOW-VOLATILITY 30",
    "NIFTY SMALLCAP250 MOMENTUM QUALITY 100",
    "NIFTY SMALLCAP250 QUALITY 50",
    "NIFTY TOP 10 EQUAL WEIGHT",
    "NIFTY TOP 15 EQUAL WEIGHT",
    "NIFTY TOP 20 EQUAL WEIGHT",
    "NIFTY TOTAL MARKET MOMENTUM QUALITY 50",
    "NIFTY100 ALPHA 30",
    "NIFTY100 EQUAL WEIGHT",
    "NIFTY100 LOW VOLATILITY 30",
    "NIFTY100 QUALITY 30",
    "NIFTY200 ALPHA 30",
    "NIFTY200 MOMENTUM 30",
    "NIFTY200 QUALITY 30",
    "NIFTY200 VALUE 30",
    "NIFTY50 DIVIDEND POINTS",
    "NIFTY50 EQUAL WEIGHT",
    "NIFTY50 PR 1X INVERSE",
    "NIFTY50 PR 2X LEVERAGE",
    "NIFTY50 TR 1X INVERSE",
    "NIFTY50 TR 2X LEVERAGE",
    "NIFTY50 USD",
    "NIFTY50 VALUE 20",
    "NIFTY500 EQUAL WEIGHT",
    "NIFTY500 FLEXICAP QUALITY 30",
    "NIFTY500 LOW VOLATILITY 50",
    "NIFTY500 MOMENTUM 50",
    "NIFTY500 MULTICAP MOMENTUM QUALITY 50",
    "NIFTY500 MULTIFACTOR MQVLV 50",
    "NIFTY500 QUALITY 50",
    "NIFTY500 VALUE 50"
]

STRATEGY_INDICES = {
    idx: {
        "name": f"{idx} INDEX",
        "indexName": idx
    }
    for idx in STRATEGY_LIST
}
THEMATIC_LIST = [
    "NIFTY CAPITAL MARKETS",
    "NIFTY COMMODITIES",
    "NIFTY CONGLOMERATE 50",
    "NIFTY CORE HOUSING",
    "NIFTY CPSE",
    "NIFTY ENERGY",
    "NIFTY EV & NEW AGE AUTOMOTIVE",
    "NIFTY HOUSING",
    "NIFTY INDIA CONSUMPTION",
    "NIFTY INDIA CORPORATE GROUP INDEX - ADITYA BIRLA GROUP",
    "NIFTY INDIA CORPORATE GROUP INDEX - MAHINDRA GROUP",
    "NIFTY INDIA CORPORATE GROUP INDEX - TATA GROUP",
    "NIFTY INDIA CORPORATE GROUP INDEX - TATA GROUP 25% CAP",
    "NIFTY INDIA DEFENCE",
    "NIFTY INDIA DIGITAL",
    "NIFTY INDIA INFRASTRUCTURE & LOGISTICS",
    "NIFTY INDIA INTERNET",
    "NIFTY INDIA MANUFACTURING",
    "NIFTY INDIA NEW AGE CONSUMPTION",
    "NIFTY INDIA RAILWAYS PSU",
    "NIFTY INDIA SELECT 5 CORPORATE GROUPS (MAATR)",
    "NIFTY INDIA TOURISM",
    "NIFTY INFRASTRUCTURE",
    "NIFTY IPO",
    "NIFTY MIDCAP LIQUID 15",
    "NIFTY MIDSMALL INDIA CONSUMPTION",
    "NIFTY MNC",
    "NIFTY MOBILITY",
    "NIFTY NON-CYCLICAL CONSUMER",
    "NIFTY PSE",
    "NIFTY REITS & INVITS",
    "NIFTY RURAL",
    "NIFTY SERVICES SECTOR",
    "NIFTY SHARIAH 25",
    "NIFTY SME EMERGE",
    "NIFTY TRANSPORTATION & LOGISTICS",
    "NIFTY WAVES",
    "NIFTY100 ENHANCED ESG",
    "NIFTY100 ESG",
    "NIFTY100 ESG SECTOR LEADERS",
    "NIFTY100 LIQUID 15",
    "NIFTY50 SHARIAH",
    "NIFTY500 MULTICAP INDIA MANUFACTURING 50:30:20",
    "NIFTY500 MULTICAP INFRASTRUCTURE 50:30:20",
    "NIFTY500 SHARIAH"
]

THEMATIC_INDICES = {
    idx: {
        "name": f"{idx}",
        "indexName": idx
    }
    for idx in THEMATIC_LIST
}
GOVERNMENT_SECURITIES_LIST = [
    "NIFTY 10 YR BENCHMARK G-SEC",
    "NIFTY 10 YR BENCHMARK G-SEC (CLEAN PRICE)",
    "NIFTY 11-15 YR G-SEC INDEX",
    "NIFTY 15 YR AND ABOVE G-SEC INDEX",
    "NIFTY 4-8 YR G-SEC INDEX",
    "NIFTY 5YR BENCHMARK G-SEC INDEX",
    "NIFTY 8-13 YR G-SEC",
    "NIFTY COMPOSITE G-SEC INDEX",
    "NIFTY INDIA GOVERNMENT FULLY ACCESSIBLE ROUTE (FAR) SELECT 7 BONDS INDEX (INR)",
    "NIFTY INDIA GOVERNMENT FULLY ACCESSIBLE ROUTE (FAR) SELECT 7 BONDS INDEX (USD)",
    "NIFTY INDIA SOVEREIGN GREEN BOND JAN 2028",
    "NIFTY INDIA SOVEREIGN GREEN BOND JAN 2033"
]

GOVERNMENT_SECURITIES = {
    idx: {
        "name": idx,
        "indexName": idx
    }
    for idx in GOVERNMENT_SECURITIES_LIST
}
MONEY_MARKET_LIST = [
    "NIFTY 1D RATE INDEX",
    "NIFTY FINANCIAL SERVICES 3 TO 6 MONTHS DEBT",
    "NIFTY FINANCIAL SERVICES 9 TO 12 MONTHS DEBT"
]

MONEY_MARKET = {
    idx: {
        "name": idx,
        "indexName": idx
    }
    for idx in MONEY_MARKET_LIST
}
SDL_INDICES_LIST = [
    "NIFTY 10 YEAR SDL INDEX",
    "NIFTY 3 YEAR SDL",
    "NIFTY 5 YEAR SDL"
]

SDL_INDICES = {
    idx: {
        "name": idx,
        "indexName": idx
    }
    for idx in SDL_INDICES_LIST
}
TARGET_MATURITY_LIST = [
    "NIFTY AAA BOND JUN 2025 HTM",
    "NIFTY AAA BOND PLUS G-SEC MAR 2035 30:70",
    "NIFTY AAA BOND PLUS SDL APR 2026 50:50 INDEX",
    "NIFTY AAA BOND PLUS SDL APR 2026 70:30 INDEX",
    "NIFTY AAA BOND PLUS SDL APR 2031 70:30 INDEX",
    "NIFTY AAA CPSE BOND PLUS SDL APR 2027 60:40 INDEX",
    "NIFTY AAA FINANCIAL SERVICES BOND MAR 2028",
    "NIFTY AAA FINANCIAL SERVICES BOND PLUS G-SEC APR 2027 90:10",
    "NIFTY AAA FINANCIAL SERVICES BOND PLUS G-SEC APR 2028 90:10",
    "NIFTY AAA PSU BOND PLUS SDL APR 2026 50:50 INDEX",
    "NIFTY AAA PSU BOND PLUS SDL SEP 2026 50:50 INDEX",
    "NIFTY BHARAT BOND INDEX - APRIL 2023",
    "NIFTY BHARAT BOND INDEX - APRIL 2025",
    "NIFTY BHARAT BOND INDEX - APRIL 2030",
    "NIFTY BHARAT BOND INDEX - APRIL 2031",
    "NIFTY BHARAT BOND INDEX - APRIL 2032",
    "NIFTY BHARAT BOND INDEX - APRIL 2033",
    "NIFTY CPSE BOND PLUS SDL SEP 2024 50:50 INDEX",
    "NIFTY CPSE BOND PLUS SDL SEP 2026 50:50 INDEX",
    "NIFTY G-SEC APR 2029",
    "NIFTY G-SEC DEC 2026 INDEX",
    "NIFTY G-SEC DEC 2029 INDEX",
    "NIFTY G-SEC DEC 2030 INDEX",
    "NIFTY G-SEC JUL 2027",
    "NIFTY G-SEC JUL 2031 INDEX",
    "NIFTY G-SEC JUL 2033",
    "NIFTY G-SEC JUN 2027 INDEX",
    "NIFTY G-SEC JUN 2036 INDEX",
    "NIFTY G-SEC MAY 2029",
    "NIFTY G-SEC OCT 2028 INDEX",
    "NIFTY G-SEC SEP 2027 INDEX",
    "NIFTY G-SEC SEP 2032 INDEX",
    "NIFTY PSU BOND PLUS SDL APR 2026 50:50 INDEX",
    "NIFTY PSU BOND PLUS SDL APR 2027 50:50 INDEX",
    "NIFTY PSU BOND PLUS SDL SEP 2027 40:60 INDEX",
    "NIFTY SDL APR 2026 TOP 20 EQUAL WEIGHT INDEX",
    "NIFTY SDL APR 2027 INDEX",
    "NIFTY SDL APR 2027 TOP 12 EQUAL WEIGHT INDEX",
    "NIFTY SDL APR 2031 TOP 20 EQUAL WEIGHT HTM",
    "NIFTY SDL APR 2032 TOP 12 EQUAL WEIGHT INDEX",
    "NIFTY SDL DEC 2026 INDEX",
    "NIFTY SDL DEC 2028 INDEX",
    "NIFTY SDL JUL 2026 INDEX",
    "NIFTY SDL JUL 2028",
    "NIFTY SDL JUL 2033 INDEX",
    "NIFTY SDL JUN 2027 INDEX",
    "NIFTY SDL JUNE 2028",
    "NIFTY SDL OCT 2026 INDEX",
    "NIFTY SDL PLUS AAA PSU BOND APR 2026 75:25 INDEX",
    "NIFTY SDL PLUS AAA PSU BOND APR 2028 75:25",
    "NIFTY SDL PLUS AAA PSU BOND DEC 2027 60:40 INDEX",
    "NIFTY SDL PLUS AAA PSU BOND JUL 2028 60:40 INDEX",
    "NIFTY SDL PLUS AAA PSU BOND JUL 2033 60:40 INDEX",
    "NIFTY SDL PLUS G-SEC JUN 2028 30:70 INDEX",
    "NIFTY SDL PLUS G-SEC JUN 2028 70:30 INDEX",
    "NIFTY SDL PLUS G-SEC JUN 2029 70:30 INDEX",
    "NIFTY SDL PLUS G-SEC JUNE 2027 40:60",
    "NIFTY SDL PLUS G-SEC SEP 2027 50:50 INDEX",
    "NIFTY SDL PLUS PSU BOND SEP 2026 60:40 INDEX",
    "NIFTY SDL SEP 2025 INDEX",
    "NIFTY SDL SEP 2026 INDEX",
    "NIFTY SDL SEP 2026 V1 INDEX",
    "NIFTY SDL SEP 2027 INDEX"
]

TARGET_MATURITY_INDICES = {
    idx: {
        "name": idx,
        "indexName": idx
    }
    for idx in TARGET_MATURITY_LIST
}

INDEX_OPTIONS = {
    "Multi Asset": {
        "Hybrid Indices": {
            "NIFTY AQLV 30 PLUS 5YR G-SEC 70:30 INDEX": {
                "name": "NIFTY AQLV 30 PLUS 5YR G-SEC 70:30 INDEX",
                "indexName": "NIFTY AQLV 30 PLUS 5YR G-SEC 70:30 INDEX"
            },

            "NIFTY LARGEMIDCAP250 PLUS 8-13 YR G-SEC 70:30": {
                "name": "NIFTY LARGEMIDCAP250 PLUS 8-13 YR G-SEC 70:30 INDEX",
                "indexName": "NIFTY LARGEMIDCAP250 PLUS 8-13 YR G-SEC 70:30"
            },

            "NIFTY MULTI ASSET – EQUITY : ARBITRAGE : REITS/INVITS (50:40:10)": {
                "name": "NIFTY MULTI ASSET – EQUITY : ARBITRAGE : REITS/INVITS (50:40:10)",
                "indexName": "NIFTY MULTI ASSET – EQUITY : ARBITRAGE : REITS/INVITS (50:40:10)"
            },

            "NIFTY MULTI ASSET – EQUITY : DEBT : ARBITRAGE : REITS/INVITS (50:20:20:10)": {
                "name": "NIFTY MULTI ASSET – EQUITY : DEBT : ARBITRAGE : REITS/INVITS (50:20:20:10)",
                "indexName": "NIFTY MULTI ASSET – EQUITY : DEBT : ARBITRAGE : REITS/INVITS (50:20:20:10)"
            },
            "NIFTY200 MOMENTUM 30 PLUS 8-13 YR G-SEC 75:25 INDEX": {
                "name": "NIFTY200 MOMENTUM 30 PLUS 8-13 YR G-SEC 75:25 INDEX",
                "indexName": "NIFTY200 MOMENTUM 30 PLUS 8-13 YR G-SEC 75:25 INDEX"
            },
            "NIFTY200 MOMENTUM 30 PLUS 8-13 YR G-SEC 50:50 INDEX": {
                "name": "NIFTY200 MOMENTUM 30 PLUS 8-13 YR G-SEC 50:50 INDEX",
                "indexName": "NIFTY200 MOMENTUM 30 PLUS 8-13 YR G-SEC 50:50 INDEX"
            }
        }
    },
    "Equity": {
    "Broad Market Indices": BROAD_MARKET_INDICES,
    "Sectoral Indices": SECTORAL_INDICES,
    "Strategy Indices": STRATEGY_INDICES,
    "Thematic Indices": THEMATIC_INDICES
    },
    "Fixed Income": {
    "Government Securities": GOVERNMENT_SECURITIES,
    "Money Market": MONEY_MARKET,
    "SDL Indices": SDL_INDICES,
    "Target Maturity Index": TARGET_MATURITY_INDICES
    }
}
TRI_BROAD_MARKET_LIST = [
"NIFTY 50",
"NIFTY NEXT 50",
"NIFTY 100",
"NIFTY 200",
"NIFTY 500",
"NIFTY INDIA FPI 150",
"NIFTY LARGEMIDCAP 250",
"NIFTY MICROCAP 250",
"NIFTY MIDCAP 50",
"NIFTY MIDCAP 100",
"NIFTY MIDCAP 150",
"NIFTY MIDCAP SELECT",
"NIFTY MIDSMALLCAP 400",
"NIFTY MIDSMALLCAP400 50:50",
"NIFTY NEXT 50",
"NIFTY SMALLCAP 50",
"NIFTY SMALLCAP 100",
"NIFTY SMALLCAP 250",
"NIFTY SMALLCAP 500",
"NIFTY TOTAL MARKET",
"NIFTY500 LARGEMIDSMALL EQUAL-CAP WEIGHTED",
"NIFTY500 MULTICAP 50:25:25"
]
TRI_BROAD_MARKET_INDICES = {
idx: {
"name": idx,
"indexName": idx
}
for idx in TRI_BROAD_MARKET_LIST
}
TRI_SECTORAL_LIST = [
"NIFTY AUTO",
"NIFTY BANK",
"NIFTY CEMENT",
"NIFTY CHEMICALS",
"NIFTY CONSUMER DURABLES",
"NIFTY FINANCIAL SERVICES",
"NIFTY FINANCIAL SERVICES 25/50",
"NIFTY FINANCIAL SERVICES EX-BANK",
"NIFTY FMCG",
"NIFTY HEALTHCARE",
"NIFTY IT",
"NIFTY MEDIA",
"NIFTY METAL",
"NIFTY MIDSMALL FINANCIAL SERVICES",
"NIFTY MIDSMALL HEALTHCARE",
"NIFTY MIDSMALL IT & TELECOM",
"NIFTY OIL & GAS",
"NIFTY PHARMA",
"NIFTY PRIVATE BANK",
"NIFTY PSU BANK",
"NIFTY REALTY",
"NIFTY REITS & REALTY",
"NIFTY500 HEALTHCARE"
]

TRI_SECTORAL_INDICES = {
idx: {
"name": idx,
"indexName": idx
}
for idx in TRI_SECTORAL_LIST
}
TRI_STRATEGY_LIST = [
"NIFTY 50 FUTURES TR",
"NIFTY ALPHA 50",
"NIFTY ALPHA LOW-VOLATILITY 30",
"NIFTY ALPHA QUALITY LOW-VOLATILITY 30",
"NIFTY ALPHA QUALITY VALUE LOW-VOLATILITY 30",
"NIFTY DIVIDEND OPPORTUNITIES 50",
"NIFTY GROWTH SECTORS 15",
"NIFTY HIGH BETA 50",
"NIFTY LOW VOLATILITY 50",
"NIFTY MIDCAP150 MOMENTUM 50",
"NIFTY MIDCAP150 QUALITY 50",
"NIFTY MIDSMALLCAP400 MOMENTUM QUALITY 100",
"NIFTY QUALITY LOW-VOLATILITY 30",
"NIFTY SMALLCAP250 MOMENTUM QUALITY 100",
"NIFTY SMALLCAP250 QUALITY 50",
"NIFTY TOP 10 EQUAL WEIGHT",
"NIFTY TOP 15 EQUAL WEIGHT",
"NIFTY TOP 20 EQUAL WEIGHT",
"NIFTY TOTAL MARKET MOMENTUM QUALITY 50",
"NIFTY100 ALPHA 30",
"NIFTY100 EQUAL WEIGHT",
"NIFTY100 LOW VOLATILITY 30",
"NIFTY100 QUALITY 30",
"NIFTY200 ALPHA 30",
"NIFTY200 MOMENTUM 30",
"NIFTY200 QUALITY 30",
"NIFTY200 VALUE 30",
"NIFTY50 EQUAL WEIGHT",
"NIFTY50 VALUE 20",
"NIFTY500 EQUAL WEIGHT",
"NIFTY500 FLEXICAP QUALITY 30",
"NIFTY500 LOW VOLATILITY 50",
"NIFTY500 MOMENTUM 50",
"NIFTY500 MULTICAP MOMENTUM QUALITY 50",
"NIFTY500 MULTIFACTOR MQVLV 50",
"NIFTY500 QUALITY 50",
"NIFTY500 VALUE 50"
]

TRI_STRATEGY_INDICES = {
idx: {
"name": idx,
"indexName": idx
}
for idx in TRI_STRATEGY_LIST
}
TRI_THEMATIC_LIST = [
"NIFTY CAPITAL MARKETS",
"NIFTY COMMODITIES",
"NIFTY CONGLOMERATE 50",
"NIFTY CORE HOUSING",
"NIFTY CPSE",
"NIFTY ENERGY",
"NIFTY EV & NEW AGE AUTOMOTIVE",
"NIFTY HOUSING",
"NIFTY INDIA CONSUMPTION",
"NIFTY INDIA CORPORATE GROUP INDEX - ADITYA BIRLA GROUP",
"NIFTY INDIA CORPORATE GROUP INDEX - MAHINDRA GROUP",
"NIFTY INDIA CORPORATE GROUP INDEX - TATA GROUP",
"NIFTY INDIA CORPORATE GROUP INDEX - TATA GROUP 25% CAP",
"NIFTY INDIA DEFENCE",
"NIFTY INDIA DIGITAL",
"NIFTY INDIA INFRASTRUCTURE & LOGISTICS",
"NIFTY INDIA INTERNET",
"NIFTY INDIA MANUFACTURING",
"NIFTY INDIA NEW AGE CONSUMPTION",
"NIFTY INDIA RAILWAYS PSU",
"NIFTY INDIA SELECT 5 CORPORATE GROUPS (MAATR)",
"NIFTY INDIA TOURISM",
"NIFTY INFRASTRUCTURE",
"NIFTY IPO",
"NIFTY MIDCAP LIQUID 15",
"NIFTY MIDSMALL INDIA CONSUMPTION",
"NIFTY MNC",
"NIFTY MOBILITY",
"NIFTY NON-CYCLICAL CONSUMER",
"NIFTY PSE",
"NIFTY REITS & INVITS",
"NIFTY RURAL",
"NIFTY SERVICES SECTOR",
"NIFTY SHARIAH 25",
"NIFTY SME EMERGE",
"NIFTY TRANSPORTATION & LOGISTICS",
"NIFTY WAVES",
"NIFTY100 ENHANCED ESG",
"NIFTY100 ESG",
"NIFTY100 ESG SECTOR LEADERS",
"NIFTY100 LIQUID 15",
"NIFTY50 SHARIAH",
"NIFTY500 MULTICAP INDIA MANUFACTURING 50:30:20",
"NIFTY500 MULTICAP INFRASTRUCTURE 50:30:20",
"NIFTY500 SHARIAH"
]

TRI_THEMATIC_INDICES = {
idx: {
"name": idx,
"indexName": idx
}
for idx in TRI_THEMATIC_LIST
}
TRI_HIERARCHY = {
    "Equity": [
        "Broad Market Indices",
        "Sectoral Indices",
        "Strategy Indices",
        "Thematic Indices"
    ]
}
TRI_OPTIONS = {
"Broad Market Indices": TRI_BROAD_MARKET_INDICES,
"Sectoral Indices": TRI_SECTORAL_INDICES,
"Strategy Indices": TRI_STRATEGY_INDICES,
"Thematic Indices": TRI_THEMATIC_INDICES
}
